version: '3.4'

networks:
  rdf.arcana.api:

services:
  rdf.arcana.api:
    image: rdf.arcana.api
    build:
      context: .
      dockerfile: RDF.Arcana.API/Dockerfile
    ports:
    - "5078:5078"
    - "5079:5079"
    depends_on: 
      - arcana.database
    networks: 
      - rdf.arcana.api
 
  arcana.database: 
     image: mcr.microsoft.com/mssql/server:2022-latest
     container_name: arcana.database
     environment:
         - ACCEPT_EULA=Y
         - MSSQL_SA_PASSWORD=Aldrin004!
         - DB_NAME=rdf_arcana
         - DB_SA_PASSWORD=Aldrin004! 
     networks:
       - rdf.arcana.api
     volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
      - arcana-volume:/var/lib/mysql
     ports:
        - "5070:1433"

  arcana-blob-storage:
      image: mcr.microsoft.com/azure-storage/azurite:latest
      container_name: arcana.blob-storage
      volumes: 
        - ./.containers/blob_storage/data:/data
      ports: 
        - "10000:10000"
        - "10001:10001"
      command: "azurite-blob --blobHost 0.0.0.0 -l /data"

volumes:
  arcana-volume: